[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webrtc-unreliable = {version = "0.5.3"}
clap = "3.0"
env_logger = "0.9"
futures = { version = "0.3" }
hyper = { version = "0.14", features = ["http1", "runtime", "server", "stream"] }
tokio = { version = "1.0", features = ["macros", "net", "rt-multi-thread"] }
log = "0.4"
# webrtc = "0.8.0"
webrtc = { path = "../../webrtc/webrtc" }
reqwest = "0.11.18"
tinyjson = "2.5.1"
regex = "1.9.1"
bytes = "1.4.0"
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0"
base64 = "0.21.2"